// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5mG7U7c79KW801VkM5nWbwd3oEF9buQE',
    appId: '1:306539867651:web:f3534e61be49d0da212836',
    messagingSenderId: '306539867651',
    projectId: 'bdparcial4',
    authDomain: 'bdparcial4.firebaseapp.com',
    storageBucket: 'bdparcial4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzwejFCNNdLh8SwOnM_w_ek2sNbNVgWXE',
    appId: '1:306539867651:android:05e95ced1fc1d096212836',
    messagingSenderId: '306539867651',
    projectId: 'bdparcial4',
    storageBucket: 'bdparcial4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9uiLKEnpyIDlFZ2xs_93cFl4v3ZfNNx0',
    appId: '1:306539867651:ios:4160582391fedaa2212836',
    messagingSenderId: '306539867651',
    projectId: 'bdparcial4',
    storageBucket: 'bdparcial4.appspot.com',
    iosClientId: '306539867651-p2safn7i7bp9k3dve8s62fvj5go9838j.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial042550302018',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9uiLKEnpyIDlFZ2xs_93cFl4v3ZfNNx0',
    appId: '1:306539867651:ios:4160582391fedaa2212836',
    messagingSenderId: '306539867651',
    projectId: 'bdparcial4',
    storageBucket: 'bdparcial4.appspot.com',
    iosClientId: '306539867651-p2safn7i7bp9k3dve8s62fvj5go9838j.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial042550302018',
  );
}
